name: pili_variety_classification
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_tflite: ^1.0.1
  image_picker: ^0.8.9
  scanning_effect: ^1.0.4
  image: ^3.3.0
  contained_tab_bar_view: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/label/
    - assets/models/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        # ITALIC
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic

    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova-Black.otf
          weight: 900
        - asset: assets/fonts/ProximaNova-Extrabold.otf
          weight: 800
        - asset: assets/fonts/ProximaNova-Bold.otf
          weight: 700
        - asset: assets/fonts/ProximaNova-Bold-Italic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/ProximaNova-Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/ProximaNova-Regular.otf
          weight: 400
        - asset: assets/fonts/ProximaNova-Thin.otf
          weight: 100

    - family: Mont
      fonts:
        - asset: assets/fonts/Mont-Black.ttf
          weight: 900
        - asset: assets/fonts/Mont-Heavy.ttf
          weight: 800
        - asset: assets/fonts/Mont-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mont-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Mont-Regular.ttf
          weight: 400
        - asset: assets/fonts/Mont-Light.ttf
          weight: 300
        - asset: assets/fonts/Mont-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Mont-Thin.ttf
          weight: 100
        # ITALIC
        - asset: assets/fonts/Mont-Black-Italic.ttf
          weight: 900
        - asset: assets/fonts/Mont-Heavy-Italic.ttf
          weight: 800
        - asset: assets/fonts/Mont-Bold-Italic.ttf
          weight: 700
        - asset: assets/fonts/Mont-Semibold-Italic.ttf
          weight: 600
        - asset: assets/fonts/Mont-Regular-Italic.ttf
          weight: 400
        - asset: assets/fonts/Mont-Light-Italic.ttf
          weight: 300
        - asset: assets/fonts/Mont-ExtraLight-Italic.ttf
          weight: 200
        - asset: assets/fonts/Mont-Thin-Italic.ttf
          weight: 100
